---
- name: Install state sync script
  hosts: '{{ target }}'
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - support_snapshot
    - support_state_sync
    - support_resync
    - support_genesis
